# general
gpu_id: 6
use_gpu: True
seed: 42
state: INFO
reproducibility: True
data_path: 'dataset/'
checkpoint_dir: 'saved'
show_progress: True
save_dataset: False
save_dataloaders: False

# dataset
load_col:
    inter: [review_id, user_id, business_id, stars, useful, funny, cool, date]
#    item: ['business_id','item_name','address','city','state','postal_code','latitude','longitude','item_stars','item_review_count','is_open','categories']
MAX_ITEM_LIST_LENGTH: 50
USER_ID_FIELD: user_id
ITEM_ID_FIELD: business_id
RATING_FIELD: stars
TIME_FIELD: date

# Filtering
val_interval: {'date': "[1546264800,1577714400]"}
filter_inter_by_user_or_item: True
user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

two_level: True
rich_calibrated_combine: 'none'
trainable_mask_loss_weight: True
combine_option: 'gate'
use_position_embedding: False
use_order: True
use_distance: True
mask_loss_weight: 0.03


n_layers: 3
n_heads: 8
hidden_size: 128
inner_size: 64
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: 'gelu'
layer_norm_eps: 1e-12
initializer_range: 0.02
loss_type: 'CE'

